FROM golang:1.24.5-alpine AS builder
WORKDIR /go/src/app
ENV GO111MODULE=on
COPY go.mod .
COPY go.sum .
RUN apk add --no-cache git
RUN go mod download
COPY . .
RUN go build -o /go/bin/app

FROM alpine:3.20
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=builder /go/bin/app ./app
EXPOSE 8080
CMD ["./app"]